### ISSUE TITLE
Unable to set Response Curves (Stick Sensitivity)

### ISSUE THREAD

**Issue by MrJayPockets** [steffalon/dualsense-edge-profile-web-application#6] opened 2024-01-30 05:39 UTC
Hello,

I am unable to set the Stick Sensitivity on both the Left Stick and the Right Stick. I have tried various options such as Digital, Quick, and Precise but whenever I swap to Button Assignments and back it goes from the chosen sensitivity to Default.

After saving and closing the page, I saw that the profile had been saved on the Controller but checking Gamepad Tester it looks like the value sensitivity doesn't change from the default. This was tested by holding the right stick at a certain value and swapping between the 4 different profiles created. I assumed it would change right stick values but I'm not seeing it change.

I'd love to see this feature fixed if possible since I don't own a PS5. Thank you so much for your work, this is exactly what I've been looking for and everything has been looking awesome!

**Comment by steffalon** [comment] 2024-02-04 13:21
Thank you for creating this issue. I might have resolved it in the new build. Could you test this patch? It is already deployed at https://ds-edge-configurator.com/.

You can close this issue when it is fixed on your end. If not, let me know! 😄

**Comment by GittyUser54321** [comment] 2024-02-04 21:43
> Thank you for creating this issue. I might have resolved it in the new build. Could you test this patch? It is already deployed at https://ds-edge-configurator.com/.
> 
> You can close this issue when it is fixed on your end. If not, let me know! 😄

Can confirm it works as intended now. Thank you

**Comment by steffalon** [comment] 2024-02-10 10:50
Thank you for the confirmation @GittyUser54321. Closing this issue as **resolved**

**Closed as completed by steffalon** 2024-02-10 10:50 UTC
